
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(QT_REQUESTED_MAJOR_VERSION 6)
endif()

if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(QT_REQUESTED_MAJOR_VERSION 5)
endif()

find_package(QT NAMES Qt${QT_REQUESTED_MAJOR_VERSION} COMPONENTS REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Widgets REQUIRED)
find_package(Qt${QT_VERSION_MAJOR}Multimedia REQUIRED)
find_package(Qt${QT_VERSION_MAJOR}UiTools REQUIRED)
